networks:
  internal:
    external : false

services:
  ui:
    container_name: ui
    build: ui
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app/
    ports:
      - "8080:8080"
    networks:
      - internal

